version: '3'
services:
  mongodb:
        image: mongo:latest
        ports:
            - '27018:27017'
        container_name: mongodb
        restart: unless-stopped
        volumes:
            - '/your-storage-path:/data/db'
        command: [--auth]
        environment:
            - 'MONGO_INITDB_DATABASE=mydb'
            - 'MONGO_INITDB_ROOT_USERNAME=root'
            - 'MONGO_INITDB_ROOT_PASSWORD=hguYd332'
        networks:
            - mongo_network
  mongo-express:
        image: mongo-express
        container_name: mxpress
        environment:
            - 'ME_CONFIG_MONGODB_ADMINUSERNAME=root'
            - 'ME_CONFIG_MONGODB_ADMINPASSWORD=hguYd332'
            - 'ME_CONFIG_MONGODB_URL=mongodb://root:hguYd332@mongodb:27017'
            - 'ME_CONFIG_BASICAUTH_USERNAME=admin'
            - 'ME_CONFIG_BASICAUTH_PASSWORD=hgsd2DF'
        links:
            - mongo
        restart: unless-stopped
        ports:
            - 8686:8081
        networks:
            - mongo_network
networks:
    mongo_network: